name: LemonKernel

on:
  push:
    branches:
      - Lineage-20

jobs:
  build:
    name: Build LemonKernel
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set Current Date
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential gcc-aarch64-linux-gnu -y

      - name: Set up Android environment
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '13'
          build-tools-version: '32.0.0'
          target-platform: 'android-33'

      - name: Cloning script
        run: git clone https://github.com/GiovanYCringe/kernel-build build/

      - name: Build LemonKernel
        run: ./build/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LemonKernel
          path: Lemonade-a505f-*.zip


